In [1]:
import numpy as np

In [3]:
#create a vector as a row
vector_row = np.array([1,2,3])
print(vector_row)

[1 2 3]


In [5]:
k = []
for i in range(5):
    k.append(i)
print(k)
kk = np.array(k)
print(kk)

[0, 1, 2, 3, 4]
[0 1 2 3 4]


In [6]:
np.mean(vector_row)
print(np.mean(vector_row))

2.0


In [7]:
#create vector as a column
vector_column = np.array([[1],[2],[3]])
print(vector_column)

[[1]
 [2]
 [3]]


In [9]:
xx = np.array([[1,2],[2],[3]])
print(xx)

[list([1, 2]) list([2]) list([3])]


In [11]:
#arange([start],stop,[step])
np.arange(0,10,2)
print(np.arange(0,10,2))

[0 2 4 6 8]


In [14]:
#start, stop, number of ponts evenly spaced
lin_arr = np.linspace(0,10,5)
print(lin_arr)

[ 0.   2.5  5.   7.5 10. ]


In [16]:
my_rand = np.random.rand(4)
print(my_rand)

[0.40015201 0.81523252 0.81287742 0.03370569]


In [17]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [18]:
#create an array of all zeros
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [23]:
#create an array of all ones
b = np.ones((2,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
#create a constant array
c = np.full((3,2),7)
print(c)

[[7 7]
 [7 7]
 [7 7]]


In [26]:
#create a 4x4 identity matrix
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
#Create an array filled with random values
e = np.random.random((2,2))
print(e)

[[0.09007879 0.71516703]
 [0.8409199  0.81420096]]


In [29]:
#create a vector as a Row
vector_row = np.array([1,2,3,4,5,6])
print(vector_row)
#create a matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
a = matrix[:,1:3]
print(a)

[[2 3]
 [5 6]
 [8 9]]


In [38]:
print(vector_row)
print(vector_row[1:6:2])
print(vector_row[:3])
print(vector_row[ : :2])
print(vector_row[3:])
print(vector_row[-1])

[1 2 3 4 5 6]
[2 4 6]
[1 2 3]
[1 3 5]
[4 5 6]
6


In [43]:
#select 3rd element of a vector
print(vector_row[2])

#select 2nd row 2nd column
print(matrix[1,1])
print(matrix[1][1])

#select all element of a vector
print(vector_row[:])

#select the first 2 rows and all the columns of the matrix
print(matrix[:2,:])

#select all row and 2nd column of the matrix
print(matrix[:,1:2])

3
5
5
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


In [49]:
matrix = np.array([[1,2,3],[4,5,6],[7,1,9]])
print(matrix)
print(matrix.shape)
print(matrix.size)
#View the number of DImensions
print(matrix.ndim)

[[1 2 3]
 [4 5 6]
 [7 1 9]]
(3, 3)
9
2


In [52]:
#index of the higest value in the array
matrix.argmax(axis=1)
#axis = 0 means, among the rows whose value is max.
#axis = 1 means, among the columns whose value is max

array([2, 2, 2], dtype=int64)

In [53]:
matrix.max()
print(matrix.max())

9


In [56]:
#Lowest value of the matrix
print(matrix.min())
#Index of the lowest value of the matrix
print(matrix.argmin())

1
0


In [58]:
print(matrix)
print(np.max(matrix))
print(np.min(matrix))

print(np.max(matrix,axis=0))#max in each columns
print(np.max(matrix,axis=1))#max in each rows

[[1 2 3]
 [4 5 6]
 [7 1 9]]
9
1
[7 5 9]
[3 6 9]


In [59]:
#Mean
print(np.mean(matrix))

#standard deviation
print(np.std(matrix))

#variance
print(np.var(matrix))

4.222222222222222
2.615244954653293
6.8395061728395055


In [64]:
#Reshape
print(matrix.reshape(9,1))

#Here -1 says as many columns as needed and 1 row
print(matrix.reshape(1,-1))

#If we provide only 1 value reshape would return a 1D array of that length
print(matrix.reshape(9))

#We can also use the flatten method to convert a matrix to 1D array
print(matrix)
print(matrix.flatten())

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [1]
 [9]]
[[1 2 3 4 5 6 7 1 9]]
[1 2 3 4 5 6 7 1 9]
[[1 2 3]
 [4 5 6]
 [7 1 9]]
[1 2 3 4 5 6 7 1 9]


In [65]:
#transpose of a matrix
print(matrix.T)

[[1 4 7]
 [2 5 1]
 [3 6 9]]


In [66]:
#calculate the Determinant
print(np.linalg.det(matrix))
#calculate the rank
print(np.linalg.matrix_rank(matrix))

-42.00000000000001
3


In [68]:
#Calculate the Eigenvalues and Eigenvectors of t hat matrix
eigenvalues ,eigenvectors=np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[12.88425552 -1.0347066   3.15045109]
[[-0.28586166 -0.81853596 -0.22734898]
 [-0.66793858 -0.02792403 -0.87758407]
 [-0.68712529  0.5737762   0.42208843]]


In [69]:
#Create vector_1
vector_1 = np.array([1,2,3])
#Create vector_2
vector_2 = np.array([4,5,6])
#Calculate Dot product
print(np.dot(vector_1,vector_2))
#Alternatively you can use @ to calculate dot products
print(vector_1 @ vector_2)
print(vector_1.dot(vector_2))

32
32
32


In [71]:
#Create matrix_1
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
#Create matrix_2
matrix_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

#Add the 2 matrices
print(np.add(matrix_1,matrix_2))

#Subtraction
print(np.subtract(matrix_1,matrix_2))

#multiplication element wise, not dot product
print(matrix_1 * matrix_2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [72]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,2]])
print(matrix)
#Calculate its inverse
print(np.linalg.inv(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 2]]
[[-1.80952381  0.95238095 -0.14285714]
 [ 1.61904762 -0.9047619   0.28571429]
 [-0.14285714  0.28571429 -0.14285714]]


In [75]:
data = np.array([[1,2,3],[4,5,6],[7,8,2]])
r = np.array([1,2,3])
print(data[0])
print(data[0].T)
print(np.dot(r,data[0].T))

[1 2 3]
[1 2 3]
14


In [76]:
ds = []
for i in range(3):
    val = np.dot(r,data[i].T) #For each row from data
    ds.append(val)
print(ds)

[14, 32, 29]


In [77]:
def sigmoid(z):
    return 1/(1+np.exp(-z))
sigmoid(1)

0.7310585786300049

In [78]:
a = np.array([1,3])
b = np.array([4,5])
np.dot(a,b.T)

19

In [83]:
#implementing gradient method.

for theta[0], 
             row_0=(pred_y[0] -  acutal_y[0]) X[0][0]  #as theta zero in colum0
             row_1=(pred_y[1] -  acutal_y[1]) X[1][0]  #as theta zero in colum0
             row_2=(pred_y[2] -  acutal_y[2]) X[2][0]  #as theta zero in colum0
             row_3=(pred_y[3] -  acutal_y[3]) X[3][0]  #as theta zero in colum0
             row_4=(pred_y[4] -  acutal_y[4]) X[4][0]  #as theta zero in colum0
             row_5=(pred_y[5] -  acutal_y[5]) X[5][0]  #as theta zero in colum0
             row_6=(pred_y[6] -  acutal_y[6]) X[6][0]  #as theta zero in colum0
             
total_grad=row_0 + row_1 + row_2 + row_3 + row_4 + row_5 + row_6
avg= total_grad/7
    
Now, for theta[1]
             row_0=(pred_y[0] -  acutal_y[0]) X[0][1]   
             row_1=(pred_y[1] -  acutal_y[1]) X[1][1]   
             row_2=(pred_y[2] -  acutal_y[2]) X[2][1]  
             row_3=(pred_y[3] -  acutal_y[3]) X[3][1]  
             row_4=(pred_y[4] -  acutal_y[4]) X[4][1]   
             row_5=(pred_y[5] -  acutal_y[5]) X[5][1]   
             row_6=(pred_y[6] -  acutal_y[6]) X[6][1]   
             
total_grad=row_0 + row_1 + row_2 + row_3 + row_4 + row_5 + row_6
avg= total_grad/7
#Output should be [0.42857143 8.57142857]

SyntaxError: invalid syntax (<ipython-input-83-9e9397e49b95>, line 3)