In [2]:
import numpy as np
from sklearn import datasets

In [3]:
iris =  datasets.load_iris() 
x = iris.data[:100]  
y = iris.target[:100]


x2d=[]
for i0,i1,i2,i3 in x:
    tt = [1,i0,i1,i2,i3]
    x2d.append(tt)

#print(x2d)
print(x2d[5])

[1, 5.4, 3.9, 1.7, 0.4]


In [4]:
print (x[:3])
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [111]:
X = np.array(x2d)
print(X.shape)

(100, 5)


In [112]:
theta = [0,0,0,0,0]
z = []
for i in range(100):
    z.append( (x2d[i][0]*theta[0]) + (x2d[i][1]*theta[1]) + (x2d[i][1]*theta[2]) + (x2d[i][1]*theta[3]) + (x2d[i][1]*theta[4]) )
print(z)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [113]:
yhead = []
for i in range(100):
    yhead.append(1/ (1+np.exp(-1*z[i])) )
print(yhead)

[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]


In [114]:
print(1/(1+np.exp(-1)))

0.7310585786300049


In [115]:
dtzero = 0.0
for i in range(100):
    dtzero = dtzero + ((y[i]-yhead[i])*x2d[i][0])
dtzero = (1.0/100.0)*dtzero*-1.0
print(dtzero)

-0.0


In [116]:
dtone = 0.0
for i in range(100):
    dtone = dtone + ((y[i]-yhead[i])*x2d[i][1])
dtone = (1.0/100.0)*dtone*-1.0
print(dtone)

-0.23249999999999993


In [117]:
dttwo = 0.0
for i in range(100):
    dttwo = dttwo + ((y[i]-yhead[i])*x2d[i][2])
dttwo = (1.0/100.0)*dttwo*-1.0
print(dttwo)

0.16450000000000004


In [118]:
dtthree = 0.0
for i in range(100):
    dtthree = dtthree + ((y[i]-yhead[i])*x2d[i][3])
dtthree = (1.0/100.0)*dtthree*-1.0
print(dtthree)

-0.6995


In [119]:
dtfour = 0.0
for i in range(100):
    dtfour = dtfour + ((y[i]-yhead[i])*x2d[i][4])
dtfour = (1.0/100.0)*dtfour*-1.0
print(dtfour)

-0.26999999999999996


In [120]:
print(dtzero,dtone,dttwo,dtthree,dtfour)

-0.0 -0.23249999999999993 0.16450000000000004 -0.6995 -0.26999999999999996


In [121]:
l = 0.1
th = [0,0,0,0,0]

for i in range(5000):
    z2 = []
    for j in range(100):
        z2.append( (x2d[j][0]*th[0]) + (x2d[j][1]*th[1]) + (x2d[j][2]*th[2]) + (x2d[j][3]*th[3]) + (x2d[j][4]*th[4]) )
    yh = []
    for j in range(100):
        yh.append(1/ (1+np.exp(-1*z2[j])) )
        
    dt = [0.0,0.0,0.0,0.0,0.0]
    for j in range(100):
        dt[0] = dt[0] + ((y[j]-yh[j])*x2d[j][0])
    dt[0] = (1.0/100.0)*dt[0]*-1.0
    #print(dt[0])
    
    for j in range(100):
        dt[1] = dt[1] + ((y[j]-yh[j])*x2d[j][1])
    dt[1] = (1.0/100.0)*dt[1]*-1.0
    #print(dt[1])
    
    for j in range(100):
        dt[2] = dt[2] + ((y[j]-yh[j])*x2d[j][2])
    dt[2] = (1.0/100.0)*dt[2]*-1.0
    #print(dt[1])
    
    for j in range(100):
        dt[3] = dt[3] + ((y[j]-yh[j])*x2d[j][3])
    dt[3] = (1.0/100.0)*dt[3]*-1.0
    #print(dt[1])
    
    for j in range(100):
        dt[4] = dt[4] + ((y[j]-yh[j])*x2d[j][4])
    dt[4] = (1.0/100.0)*dt[4]*-1.0
    #print(dt[1])
    
    th[0] = th[0]-(l*dt[0])
    th[1] = th[1]-(l*dt[1])
    th[2] = th[2]-(l*dt[2])
    th[3] = th[3]-(l*dt[3])
    th[4] = th[4]-(l*dt[4])
    
print(th)

[-0.4721436607680966, -0.7376963469924396, -2.7039169554388933, 4.147169103700772, 1.8579027222449944]


In [122]:
zp = []
for i in range(100):
    zp.append( (x2d[i][0]*th[0]) + (x2d[i][1]*th[1]) + (x2d[i][2]*th[2]) + (x2d[i][3]*th[3]) + (x2d[i][4]*th[4]) )
print(zp)


[-7.520487084835585, -6.0209893377176495, -6.828950369777019, -5.655355218793731, -7.71710914568023, -7.207631495549643, -6.695456943570976, -6.761608844222374, -5.381749468677542, -6.06245439511596, -7.867862469651018, -6.199352664453809, -6.1330099752429055, -7.008312532856917, -10.218266826189893, -9.61033269810698, -8.866499137029953, -7.334696812611085, -7.344338976327986, -7.731154988872675, -6.227253562279197, -7.2749730211042865, -9.080898248363564, -5.178182145964077, -4.955201933343577, -5.265325151676739, -5.975311389403297, -7.179539809164752, -7.323865023990939, -5.584799638666787, -5.388177577822141, -6.685106838570351, -8.987680254652586, -9.708307492439786, -5.876664122891461, -7.464976184244829, -8.230282534002637, -7.829129783205486, -6.066858074591508, -6.835378478921618, -7.67564408828192, -4.062095568259027, -6.607641465679288, -5.874122540498189, -5.886497075167867, -5.761429430793907, -7.502228350727098, -6.340463824707699, -7.794092834951775, -6.905934059048562,

In [123]:
yheadP = []
for i in range(100):
    yheadP.append(1/ (1+np.exp(-1*zp[i])) )
print(yheadP)

[0.0005415751030701254, 0.002421389660662142, 0.0010808237705762322, 0.003486531618428552, 0.0004449475302817851, 0.0007403613862787532, 0.0012349896414335533, 0.0011560277074402579, 0.004578706749602936, 0.002323268226454426, 0.0003827053261897006, 0.0020266292174737047, 0.0021653404818179453, 0.0009035162544760099, 3.649616676518816e-05, 6.702802594295079e-05, 0.00014101558207022628, 0.0006520762196770206, 0.0006458230500650368, 0.0004387442759991403, 0.001970975890309864, 0.0006921793634918816, 0.0001138063701403274, 0.0056066350224247205, 0.006997349259498693, 0.005141144508185292, 0.002534271960979351, 0.0007614382054250821, 0.0006591730820819357, 0.0037404583930941066, 0.004549502191371576, 0.0012478222588042957, 0.00012492397740565824, 6.07727982028014e-05, 0.002796282779475353, 0.000572470805283545, 0.0002663900527443234, 0.0003978133328314908, 0.002313083404644949, 0.00107390583697537, 0.000463776421407144, 0.01692163979495001, 0.0013481923717238743, 0.0028033788527958734, 0.0

In [124]:
for i in range(100):
    if yheadP[i]>0.5:
        yheadP[i] = 1
    else:
        yheadP[i] = 0
print(yheadP)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [125]:
accuracy = 0
for i in range(100):
    if(y[i]==yheadP[i]):
        accuracy = accuracy + 1
print(accuracy)

100


In [127]:
ny = iris.target
print(ny.shape)


(150,)


In [128]:
print(ny)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [131]:
for i in range(len(ny)):
    if(i==0):
        ny[i] = 1
    else:
        ny[i] = 0